/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../services/auth/auth.service';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import17 from 'ionic-angular/config/config';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from 'ionic-angular/components/app/app';
import * as import20 from 'ionic-angular/util/keyboard';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from 'ionic-angular/navigation/view-controller';
import * as import23 from 'ionic-angular/components/tabs/tabs';
import * as import24 from 'ionic-angular/components/button/button';
import * as import25 from 'ionic-angular/components/content/content';
export class Wrapper_Login {
  context:import0.Login;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.Login(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_Login_Host:import2.RenderComponentType = (null as any);
class _View_Login_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Login_0_4:Wrapper_Login;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Login_Host0,renderType_Login_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Login0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Login_0_4 = new Wrapper_Login(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.NavController));
    this._appEl_0.initComponent(this._Login_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Login_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Login) && (0 === requestNodeIndex))) { return this._Login_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Login_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Login_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Login_Host === (null as any))) { (renderType_Login_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Login_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginNgFactory:import11.ComponentFactory<import0.Login> = new import11.ComponentFactory<import0.Login>('page-login',viewFactory_Login_Host0,import0.Login);
const styles_Login:any[] = ([] as any[]);
var renderType_Login:import2.RenderComponentType = (null as any);
class _View_Login0 extends import1.AppView<import0.Login> {
  _anchor_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import12.Wrapper_NgIf;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import12.Wrapper_NgIf;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Login0,renderType_Login,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import13.TemplateRef_(this._appEl_0,viewFactory_Login1);
    this._NgIf_0_6 = new import12.Wrapper_NgIf(this._appEl_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import3.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import13.TemplateRef_(this._appEl_2,viewFactory_Login2);
    this._NgIf_2_6 = new import12.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this.init(([] as any[]),[
      this._anchor_0,
      this._text_1,
      this._anchor_2
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import14.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    if (((token === import13.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import14.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:boolean = !this.context.auth.authenticated();
    this._NgIf_0_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_0_6.detectChangesInternal(this,this._anchor_0,throwOnChange);
    const currVal_1:any = this.context.auth.authenticated();
    this._NgIf_2_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_Login0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Login> {
  if ((renderType_Login === (null as any))) { (renderType_Login = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_Login,{})); }
  return new _View_Login0(viewUtils,parentInjector,declarationEl);
}
class _View_Login1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Content_0_4:import15.Wrapper_Content;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Button_2_4:import16.Wrapper_Button;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Login1,renderType_Login,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import15.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import15.Wrapper_Content(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import19.App),this.parentInjector.get(import20.Keyboard),this.parentInjector.get(import21.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import23.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'block','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'Login',(null as any));
    compView_2.create(this._Button_2_4.context,[([] as any[]).concat([this._text_3])],(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n  \n',(null as any));
    compView_0.create(this._Content_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_2_4.context; }
    if (((token === import25.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Content_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = '';
    this._Button_2_4.check_block(currVal_2,throwOnChange,false);
    if (this._Button_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.context.ngAfterContentInit(); } }
    const currVal_0:any = this._Content_0_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.context.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.auth.login()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Login1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Login1(viewUtils,parentInjector,declarationEl);
}
class _View_Login2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Content_0_4:import15.Wrapper_Content;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Button_2_4:import16.Wrapper_Button;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Login2,renderType_Login,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import15.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import15.Wrapper_Content(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import19.App),this.parentInjector.get(import20.Keyboard),this.parentInjector.get(import21.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import23.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'block','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'Logout',(null as any));
    compView_2.create(this._Button_2_4.context,[([] as any[]).concat([this._text_3])],(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n  \n',(null as any));
    compView_0.create(this._Content_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_2_4.context; }
    if (((token === import25.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Content_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = '';
    this._Button_2_4.check_block(currVal_2,throwOnChange,false);
    if (this._Button_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.context.ngAfterContentInit(); } }
    const currVal_0:any = this._Content_0_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.context.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.auth.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Login2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Login2(viewUtils,parentInjector,declarationEl);
}