/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from 'ionic-angular/components/menu/menu-controller';
import * as import10 from 'angular2-jwt/angular2-jwt';
import * as import11 from '@angular/core/src/zone/ng_zone';
import * as import12 from 'ionic-angular/components/loading/loading';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import17 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from 'ionic-angular/navigation/view-controller';
import * as import20 from 'ionic-angular/navigation/nav-controller-base';
import * as import21 from 'ionic-angular/components/app/app';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from 'ionic-angular/util/keyboard';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/core/src/linker/component_factory_resolver';
import * as import26 from 'ionic-angular/gestures/gesture-controller';
import * as import27 from 'ionic-angular/transitions/transition-controller';
import * as import28 from 'ionic-angular/navigation/deep-linker';
import * as import29 from '@angular/common/src/directives/ng_if';
import * as import30 from 'ionic-angular/components/nav/nav';
import * as import31 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import32 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import33 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import34 from '../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import35 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from '../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import37 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import38 from 'ionic-angular/components/navbar/navbar';
import * as import39 from 'ionic-angular/components/tabs/tabs';
import * as import40 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import43 from 'ionic-angular/components/toolbar/toolbar';
import * as import44 from '@angular/common/src/directives/ng_for';
import * as import45 from 'ionic-angular/components/list/list';
import * as import46 from 'ionic-angular/components/content/content';
import * as import47 from 'ionic-angular/components/menu/menu';
import * as import48 from '../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import49 from 'ionic-angular/components/button/button';
import * as import50 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import51 from '../node_modules/ionic-angular/components/menu/menu-close.ngfactory';
import * as import52 from 'ionic-angular/util/form';
import * as import53 from 'ionic-angular/components/item/item-reorder';
import * as import54 from 'ionic-angular/components/item/item';
import * as import55 from 'ionic-angular/components/menu/menu-close';
export class Wrapper_MyApp {
  context:import0.MyApp;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.MyApp(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MyApp_Host:import2.RenderComponentType = (null as any);
class _View_MyApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MyApp_0_4:Wrapper_MyApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp_Host0,renderType_MyApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyApp_0_4 = new Wrapper_MyApp(this.parentInjector.get(import8.Platform),this.parentInjector.get(import9.MenuController),this.parentInjector.get(import10.AuthHttp),this.parentInjector.get(import11.NgZone),this.parentInjector.get(import12.LoadingController));
    this._appEl_0.initComponent(this._MyApp_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MyApp_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MyApp) && (0 === requestNodeIndex))) { return this._MyApp_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MyApp_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MyApp_Host === (null as any))) { (renderType_MyApp_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MyApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyAppNgFactory:import14.ComponentFactory<import0.MyApp> = new import14.ComponentFactory<import0.MyApp>('ng-component',viewFactory_MyApp_Host0,import0.MyApp);
const styles_MyApp:any[] = ([] as any[]);
var renderType_MyApp:import2.RenderComponentType = (null as any);
class _View_MyApp0 extends import1.AppView<import0.MyApp> {
  _viewQuery_Nav_0:import15.QueryList<any>;
  _anchor_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import16.Wrapper_NgIf;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import16.Wrapper_NgIf;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Nav_5_4:import17.Wrapper_Nav;
  _text_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp0,renderType_MyApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import15.QueryList<any>();
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import18.TemplateRef_(this._appEl_0,viewFactory_MyApp1);
    this._NgIf_0_6 = new import16.Wrapper_NgIf(this._appEl_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import3.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this._appEl_2,viewFactory_MyApp4);
    this._NgIf_2_6 = new import16.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n\n\n',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_5,'has-header','');
    this.renderer.setElementAttribute(this._el_5,'swipeBackEnabled','false');
    this._appEl_5 = new import3.AppElement(5,(null as any),this,this._el_5);
    var compView_5:any = import17.viewFactory_Nav0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Nav_5_4 = new import17.Wrapper_Nav(this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import20.NavControllerBase,(null as any)),this.parentInjector.get(import21.App),this.parentInjector.get(import22.Config),this.parentInjector.get(import23.Keyboard),new import24.ElementRef(this._el_5),this.parentInjector.get(import11.NgZone),this.renderer,this.parentInjector.get(import25.ComponentFactoryResolver),this.parentInjector.get(import26.GestureController),this.parentInjector.get(import27.TransitionController),this.parentInjector.get(import28.DeepLinker,(null as any)));
    this._appEl_5.initComponent(this._Nav_5_4.context,([] as any[]),compView_5);
    compView_5.create(this._Nav_5_4.context,([] as any[]),(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._viewQuery_Nav_0.reset([this._Nav_5_4.context]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init(([] as any[]),[
      this._anchor_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import29.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import29.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import30.Nav) && (5 === requestNodeIndex))) { return this._Nav_5_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.authenticated();
    this._NgIf_0_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_0_6.detectChangesInternal(this,this._anchor_0,throwOnChange);
    const currVal_1:boolean = !this.context.authenticated();
    this._NgIf_2_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    const currVal_2:any = this.context.rootPage;
    this._Nav_5_4.check_root(currVal_2,throwOnChange,false);
    const currVal_3:any = 'false';
    this._Nav_5_4.check_swipeBackEnabled(currVal_3,throwOnChange,false);
    this._Nav_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_5_4.context.ngAfterViewInit(); } }
  }
}
export function viewFactory_MyApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MyApp> {
  if ((renderType_MyApp === (null as any))) { (renderType_MyApp = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_MyApp,{})); }
  return new _View_MyApp0(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Menu_0_4:import31.Wrapper_Menu;
  _query_Content_0_0:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Header_2_3:import32.Wrapper_Header;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Toolbar_4_4:import32.Wrapper_Toolbar;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _ToolbarTitle_6_4:import33.Wrapper_ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _ToolbarItem_9_3:import34.Wrapper_ToolbarItem;
  _query_Button_9_0:import15.QueryList<any>;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import16.Wrapper_NgIf;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Content_16_4:import35.Wrapper_Content;
  _text_17:any;
  _el_18:any;
  _List_18_3:import36.Wrapper_List;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _TemplateRef_20_5:any;
  _NgFor_20_6:import37.Wrapper_NgFor;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp1,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import31.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import31.Wrapper_Menu(this.parentInjector.get(import9.MenuController),new import24.ElementRef(this._el_0),this.parentInjector.get(import22.Config),this.parentInjector.get(import8.Platform),this.renderer,this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import11.NgZone),this.parentInjector.get(import26.GestureController));
    this._query_Content_0_0 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Menu_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_2_3 = new import32.Wrapper_Header(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import19.ViewController,(null as any)));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','toolbar');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import32.viewFactory_Toolbar0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Toolbar_4_4 = new import32.Wrapper_Toolbar(this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Toolbar_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import33.Wrapper_ToolbarTitle(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_6),this.renderer,this._Toolbar_4_4.context,this.parentInjector.get(import38.Navbar,(null as any)));
    this._appEl_6.initComponent(this._ToolbarTitle_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_6.create(this._ToolbarTitle_6_4.context,[([] as any[]).concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_9,'right','');
    this._ToolbarItem_9_3 = new import34.Wrapper_ToolbarItem(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_9),this.renderer,this._Toolbar_4_4.context,this.parentInjector.get(import38.Navbar,(null as any)));
    this._query_Button_9_0 = new import15.QueryList<any>();
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_11 = new import3.AppElement(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import18.TemplateRef_(this._appEl_11,viewFactory_MyApp2);
    this._NgIf_11_6 = new import16.Wrapper_NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_4.create(this._Toolbar_4_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_9]),
      ([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_8,
        this._text_13
      ]
      )
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_16 = new import3.AppElement(16,0,this,this._el_16);
    var compView_16:any = import35.viewFactory_Content0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Content_16_4 = new import35.Wrapper_Content(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import11.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import39.Tabs,(null as any)));
    this._appEl_16.initComponent(this._Content_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_18_3 = new import36.Wrapper_List(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_20 = new import3.AppElement(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import18.TemplateRef_(this._appEl_20,viewFactory_MyApp3);
    this._NgFor_20_6 = new import37.Wrapper_NgFor(this._appEl_20.vcRef,this._TemplateRef_20_5,this.parentInjector.get(import40.IterableDiffers),this.parent.ref);
    this._text_21 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_16.create(this._Content_16_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_17,
        this._el_18,
        this._text_22
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n',(null as any));
    this._query_Content_0_0.reset([this._Content_16_4.context]);
    this._Menu_0_4.context.menuContent = this._query_Content_0_0.first;
      compView_0.create(this._Menu_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_15,
        this._el_16,
        this._text_23
      ]
    )],(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._text_23
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4.context; }
    if (((token === import18.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import29.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import42.ToolbarItem) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ToolbarItem_9_3.context; }
    if (((token === import43.Toolbar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Toolbar_4_4.context; }
    if (((token === import43.Header) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Header_2_3.context; }
    if (((token === import18.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import44.NgFor) && (20 === requestNodeIndex))) { return this._NgFor_20_6.context; }
    if (((token === import45.List) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._List_18_3.context; }
    if (((token === import46.Content) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Content_16_4.context; }
    if (((token === import47.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Menu_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (<_View_MyApp0>this.parent)._Nav_5_4.context;
    this._Menu_0_4.check_content(currVal_0,throwOnChange,false);
    if (this._Menu_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._Header_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Toolbar_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._ToolbarTitle_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    this._ToolbarItem_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_2:any = this.parent.context.authenticated();
    this._NgIf_11_6.check_ngIf(currVal_2,throwOnChange,false);
    this._NgIf_11_6.detectChangesInternal(this,this._anchor_11,throwOnChange);
    if (this._Content_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    this._List_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_4:any = this.parent.context.pages;
    this._NgFor_20_6.check_ngForOf(currVal_4,throwOnChange,false);
    this._NgFor_20_6.detectChangesInternal(this,this._anchor_20,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_Button_9_0.dirty) {
        this._query_Button_9_0.reset([this._appEl_11.mapNestedViews(_View_MyApp2,(nestedView:_View_MyApp2):any => {
          return [nestedView._Button_0_4.context];
      })]);
      this._ToolbarItem_9_3.context._buttons = this._query_Button_9_0;
      this._query_Button_9_0.notifyOnChanges();
    } }
    const currVal_1:any = this._Toolbar_4_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_4,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this._Content_16_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_16,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_16_4.context.ngOnDestroy();
    this._Menu_0_4.context.ngOnDestroy();
  }
}
function viewFactory_MyApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyApp1(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import48.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp2,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'logout-btn','');
    this.renderer.setElementAttribute(this._el_0,'primary','');
    this.renderer.setElementAttribute(this._el_0,'round','');
    this.renderer.setElementAttribute(this._el_0,'small','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import48.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import48.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import22.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'Logout',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = '';
    this._Button_0_4.check_small(currVal_1,throwOnChange,false);
    const currVal_2:any = '';
    this._Button_0_4.check_round(currVal_2,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_MyApp1>this.parent)._query_Button_9_0.setDirty();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MyApp2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyApp2(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import50.Wrapper_Item;
  _ItemContent_0_5:import50.Wrapper_ItemContent;
  _MenuClose_0_6:import51.Wrapper_MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp3,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import50.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import50.Wrapper_Item(this.parent.parentInjector.get(import52.Form),this.parent.parentInjector.get(import22.Config),new import24.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import53.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import50.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import51.Wrapper_MenuClose(this.parent.parentInjector.get(import9.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_1]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import54.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Item_0_4.context; }
    if (((token === import54.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ItemContent_0_5.context; }
    if (((token === import55.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_3:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyApp3(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Menu_0_4:import31.Wrapper_Menu;
  _query_Content_0_0:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Header_2_3:import32.Wrapper_Header;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Toolbar_4_4:import32.Wrapper_Toolbar;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _ToolbarTitle_6_4:import33.Wrapper_ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _Content_11_4:import35.Wrapper_Content;
  _text_12:any;
  _el_13:any;
  _List_13_3:import36.Wrapper_List;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Item_15_4:import50.Wrapper_Item;
  _ItemContent_15_5:import50.Wrapper_ItemContent;
  _MenuClose_15_6:import51.Wrapper_MenuClose;
  _query_Label_15_0:import15.QueryList<any>;
  _query_Button_15_1:import15.QueryList<any>;
  _query_Icon_15_2:import15.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _Item_18_4:import50.Wrapper_Item;
  _ItemContent_18_5:import50.Wrapper_ItemContent;
  _MenuClose_18_6:import51.Wrapper_MenuClose;
  _query_Label_18_0:import15.QueryList<any>;
  _query_Button_18_1:import15.QueryList<any>;
  _query_Icon_18_2:import15.QueryList<any>;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp4,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import31.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import31.Wrapper_Menu(this.parentInjector.get(import9.MenuController),new import24.ElementRef(this._el_0),this.parentInjector.get(import22.Config),this.parentInjector.get(import8.Platform),this.renderer,this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import11.NgZone),this.parentInjector.get(import26.GestureController));
    this._query_Content_0_0 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Menu_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_2_3 = new import32.Wrapper_Header(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import19.ViewController,(null as any)));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','toolbar');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import32.viewFactory_Toolbar0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Toolbar_4_4 = new import32.Wrapper_Toolbar(this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Toolbar_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import33.Wrapper_ToolbarTitle(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_6),this.renderer,this._Toolbar_4_4.context,this.parentInjector.get(import38.Navbar,(null as any)));
    this._appEl_6.initComponent(this._ToolbarTitle_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_6.create(this._ToolbarTitle_6_4.context,[([] as any[]).concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_4.create(this._Toolbar_4_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
      )
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_11 = new import3.AppElement(11,0,this,this._el_11);
    var compView_11:any = import35.viewFactory_Content0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Content_11_4 = new import35.Wrapper_Content(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import11.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import39.Tabs,(null as any)));
    this._appEl_11.initComponent(this._Content_11_4.context,([] as any[]),compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_13_3 = new import36.Wrapper_List(this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','item item-block');
    this.renderer.setElementAttribute(this._el_15,'ion-item','');
    this.renderer.setElementAttribute(this._el_15,'menuClose','');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import50.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import50.Wrapper_Item(this.parentInjector.get(import52.Form),this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import53.ItemReorder,(null as any)));
    this._ItemContent_15_5 = new import50.Wrapper_ItemContent();
    this._MenuClose_15_6 = new import51.Wrapper_MenuClose(this.parentInjector.get(import9.MenuController));
    this._query_Label_15_0 = new import15.QueryList<any>();
    this._query_Button_15_1 = new import15.QueryList<any>();
    this._query_Icon_15_2 = new import15.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'Featured',(null as any));
    this._query_Label_15_0.reset(([] as any[]));
    this._Item_15_4.context.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_16]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_17 = this.renderer.createText(this._el_13,' \n            ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','item item-block');
    this.renderer.setElementAttribute(this._el_18,'ion-item','');
    this.renderer.setElementAttribute(this._el_18,'menuClose','');
    this._appEl_18 = new import3.AppElement(18,13,this,this._el_18);
    var compView_18:any = import50.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Item_18_4 = new import50.Wrapper_Item(this.parentInjector.get(import52.Form),this.parentInjector.get(import22.Config),new import24.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import53.ItemReorder,(null as any)));
    this._ItemContent_18_5 = new import50.Wrapper_ItemContent();
    this._MenuClose_18_6 = new import51.Wrapper_MenuClose(this.parentInjector.get(import9.MenuController));
    this._query_Label_18_0 = new import15.QueryList<any>();
    this._query_Button_18_1 = new import15.QueryList<any>();
    this._query_Icon_18_2 = new import15.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'Login',(null as any));
    this._query_Label_18_0.reset(([] as any[]));
    this._Item_18_4.context.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_19]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_11.create(this._Content_11_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_12,
        this._el_13,
        this._text_21
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n',(null as any));
    this._query_Content_0_0.reset([this._Content_11_4.context]);
    this._Menu_0_4.context.menuContent = this._query_Content_0_0.first;
      compView_0.create(this._Menu_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_10,
        this._el_11,
        this._text_22
      ]
    )],(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4.context; }
    if (((token === import43.Toolbar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Toolbar_4_4.context; }
    if (((token === import43.Header) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Header_2_3.context; }
    if (((token === import54.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Item_15_4.context; }
    if (((token === import54.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemContent_15_5.context; }
    if (((token === import55.MenuClose) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MenuClose_15_6.context; }
    if (((token === import54.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_18_4.context; }
    if (((token === import54.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_18_5.context; }
    if (((token === import55.MenuClose) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._MenuClose_18_6.context; }
    if (((token === import45.List) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._List_13_3.context; }
    if (((token === import46.Content) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Content_11_4.context; }
    if (((token === import47.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Menu_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (<_View_MyApp0>this.parent)._Nav_5_4.context;
    this._Menu_0_4.check_content(currVal_0,throwOnChange,false);
    if (this._Menu_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._Header_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Toolbar_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._ToolbarTitle_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    if (this._Content_11_4.detectChangesInternal(this,this._el_11,throwOnChange)) { this._appEl_11.componentView.markAsCheckOnce(); }
    this._List_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Item_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    this._ItemContent_15_5.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_5:any = '';
    this._MenuClose_15_6.check_menuClose(currVal_5,throwOnChange,false);
    this._MenuClose_15_6.detectChangesInternal(this,this._el_15,throwOnChange);
    if (this._Item_18_4.detectChangesInternal(this,this._el_18,throwOnChange)) { this._appEl_18.componentView.markAsCheckOnce(); }
    this._ItemContent_18_5.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_8:any = '';
    this._MenuClose_18_6.check_menuClose(currVal_8,throwOnChange,false);
    this._MenuClose_18_6.detectChangesInternal(this,this._el_18,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset(([] as any[]));
        this._Item_15_4.context._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset(([] as any[]));
        this._Item_15_4.context._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset(([] as any[]));
        this._Item_18_4.context._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset(([] as any[]));
        this._Item_18_4.context._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Toolbar_4_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_4,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_11_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_11,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_11_4.context.ngOnDestroy();
    this._Menu_0_4.context.ngOnDestroy();
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.opnFeatured()) !== false);
    const pd_1:any = ((<any>this._MenuClose_15_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.login()) !== false);
    const pd_1:any = ((<any>this._MenuClose_18_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyApp4(viewUtils,parentInjector,declarationEl);
}