/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './featured';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../services/auth/auth.service';
import * as import10 from 'ionic-angular/components/menu/menu-controller';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import24 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/note/note.ngfactory';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/components/toolbar/toolbar';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/components/item/item-reorder';
import * as import37 from '@angular/core/src/linker/template_ref';
import * as import38 from 'ionic-angular/components/icon/icon';
import * as import39 from 'ionic-angular/components/button/button';
import * as import40 from 'ionic-angular/components/menu/menu-toggle';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import42 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import43 from 'ionic-angular/components/navbar/navbar';
import * as import44 from '@angular/common/src/directives/ng_if';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from 'ionic-angular/components/card/card';
import * as import47 from 'ionic-angular/components/grid/grid';
import * as import48 from 'ionic-angular/components/note/note';
import * as import49 from 'ionic-angular/components/content/content';
import * as import50 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import51 from 'ionic-angular/components/avatar/avatar';
import * as import52 from '@angular/core/src/security';
export class Wrapper_Featured {
  context:import0.Featured;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.Featured(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_Featured_Host:import2.RenderComponentType = (null as any);
class _View_Featured_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Featured_0_4:Wrapper_Featured;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured_Host0,renderType_Featured_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-featured',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Featured0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Featured_0_4 = new Wrapper_Featured(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AuthService),this.parentInjector.get(import10.MenuController));
    this._appEl_0.initComponent(this._Featured_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Featured_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Featured) && (0 === requestNodeIndex))) { return this._Featured_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Featured_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Featured_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Featured_Host === (null as any))) { (renderType_Featured_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Featured_Host0(viewUtils,parentInjector,declarationEl);
}
export const FeaturedNgFactory:import12.ComponentFactory<import0.Featured> = new import12.ComponentFactory<import0.Featured>('page-featured',viewFactory_Featured_Host0,import0.Featured);
const styles_Featured:any[] = ([] as any[]);
var renderType_Featured:import2.RenderComponentType = (null as any);
class _View_Featured0 extends import1.AppView<import0.Featured> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import15.Wrapper_Button;
  _MenuToggle_4_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import17.Wrapper_ToolbarItem;
  _query_Button_4_0:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import19.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import20.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import21.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _Card_16_3:import22.Wrapper_Card;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _Item_18_4:import23.Wrapper_Item;
  _ItemContent_18_5:import23.Wrapper_ItemContent;
  _query_Label_18_0:import18.QueryList<any>;
  _query_Button_18_1:import18.QueryList<any>;
  _query_Icon_18_2:import18.QueryList<any>;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _TemplateRef_20_5:any;
  _NgIf_20_6:import24.Wrapper_NgIf;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _CardContent_31_3:import22.Wrapper_CardContent;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _Row_37_3:import25.Wrapper_Row;
  _text_38:any;
  _el_39:any;
  _Col_39_3:import25.Wrapper_Col;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _Button_41_4:import15.Wrapper_Button;
  _text_42:any;
  _el_43:any;
  _Icon_43_3:import19.Wrapper_Icon;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _Col_50_3:import25.Wrapper_Col;
  _text_51:any;
  _el_52:any;
  /*private*/ _appEl_52:import3.AppElement;
  _Button_52_4:import15.Wrapper_Button;
  _text_53:any;
  _el_54:any;
  _Icon_54_3:import19.Wrapper_Icon;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _Col_61_3:import25.Wrapper_Col;
  _text_62:any;
  _el_63:any;
  _Note_63_3:import26.Wrapper_Note;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured0,renderType_Featured,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'bar','');
    this.renderer.setElementAttribute(this._el_2,'bar-header','');
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import10.MenuController),new import28.ElementRef(this._el_4),this.parentInjector.get(import29.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import19.Wrapper_Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Featured ',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'has-header','');
    this.renderer.setElementAttribute(this._el_14,'padding','');
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import21.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import21.Wrapper_Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_16,'center','');
    this.renderer.setElementAttribute(this._el_16,'width','50%');
    this._Card_16_3 = new import22.Wrapper_Card(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n\n  ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','item item-block');
    this._appEl_18 = new import3.AppElement(18,16,this,this._el_18);
    var compView_18:any = import23.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Item_18_4 = new import23.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_18_5 = new import23.Wrapper_ItemContent();
    this._query_Label_18_0 = new import18.QueryList<any>();
    this._query_Button_18_1 = new import18.QueryList<any>();
    this._query_Icon_18_2 = new import18.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_20 = new import3.AppElement(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import37.TemplateRef_(this._appEl_20,viewFactory_Featured1);
    this._NgIf_20_6 = new import24.Wrapper_NgIf(this._appEl_20.vcRef,this._TemplateRef_20_5);
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'November 5, 1955',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_18_0.reset(([] as any[]));
    this._Item_18_4.context.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_4.context,[
      ([] as any[]).concat([this._appEl_20]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_19,
        this._text_21,
        this._el_22,
        this._text_24,
        this._el_25,
        this._text_27
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_16,'\n\n  ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_16,'img',(null as any));
    this.renderer.setElementAttribute(this._el_29,'src','http://ilovegarciniacambogia.net/wp-content/uploads/2014/02/fast-food.jpg');
    this._text_30 = this.renderer.createText(this._el_16,'\n\n  ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_16,'ion-card-content',(null as any));
    this._CardContent_31_3 = new import22.Wrapper_CardContent(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_31),this.renderer);
    this._text_32 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'p',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Wait a minute. Wait a minute, Doc. Uhhh... Are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n  ',(null as any));
    this._text_36 = this.renderer.createText(this._el_16,'\n\n  ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_16,'ion-row',(null as any));
    this._Row_37_3 = new import25.Wrapper_Row();
    this._text_38 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'ion-col',(null as any));
    this._Col_39_3 = new import25.Wrapper_Col();
    this._text_40 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'button',(null as any));
    this.renderer.setElementAttribute(this._el_41,'clear','');
    this.renderer.setElementAttribute(this._el_41,'icon-left','');
    this.renderer.setElementAttribute(this._el_41,'ion-button','');
    this.renderer.setElementAttribute(this._el_41,'small','');
    this._appEl_41 = new import3.AppElement(41,39,this,this._el_41);
    var compView_41:any = import15.viewFactory_Button0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Button_41_4 = new import15.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_41),this.renderer);
    this._appEl_41.initComponent(this._Button_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_43,'name','thumbs-up');
    this.renderer.setElementAttribute(this._el_43,'role','img');
    this._Icon_43_3 = new import19.Wrapper_Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_43),this.renderer);
    this._text_44 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'12 Likes',(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_41.create(this._Button_41_4.context,[([] as any[]).concat([
        this._text_42,
        this._el_43,
        this._text_44,
        this._el_45,
        this._text_47
      ]
    )],(null as any));
    this._text_48 = this.renderer.createText(this._el_39,'\n    ',(null as any));
    this._text_49 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_37,'ion-col',(null as any));
    this._Col_50_3 = new import25.Wrapper_Col();
    this._text_51 = this.renderer.createText(this._el_50,'\n      ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'button',(null as any));
    this.renderer.setElementAttribute(this._el_52,'clear','');
    this.renderer.setElementAttribute(this._el_52,'icon-left','');
    this.renderer.setElementAttribute(this._el_52,'ion-button','');
    this.renderer.setElementAttribute(this._el_52,'small','');
    this._appEl_52 = new import3.AppElement(52,50,this,this._el_52);
    var compView_52:any = import15.viewFactory_Button0(this.viewUtils,this.injector(52),this._appEl_52);
    this._Button_52_4 = new import15.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_52),this.renderer);
    this._appEl_52.initComponent(this._Button_52_4.context,([] as any[]),compView_52);
    this._text_53 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_54,'name','text');
    this.renderer.setElementAttribute(this._el_54,'role','img');
    this._Icon_54_3 = new import19.Wrapper_Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_54),this.renderer);
    this._text_55 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'4 Comments',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_52.create(this._Button_52_4.context,[([] as any[]).concat([
        this._text_53,
        this._el_54,
        this._text_55,
        this._el_56,
        this._text_58
      ]
    )],(null as any));
    this._text_59 = this.renderer.createText(this._el_50,'\n    ',(null as any));
    this._text_60 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_37,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_61,'center','');
    this.renderer.setElementAttribute(this._el_61,'text-center','');
    this._Col_61_3 = new import25.Wrapper_Col();
    this._text_62 = this.renderer.createText(this._el_61,'\n      ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_61,'ion-note',(null as any));
    this._Note_63_3 = new import26.Wrapper_Note();
    this._text_64 = this.renderer.createText(this._el_63,'\n        11h ago\n      ',(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n    ',(null as any));
    this._text_66 = this.renderer.createText(this._el_37,'\n  ',(null as any));
    this._text_67 = this.renderer.createText(this._el_16,'\n\n',(null as any));
    this._text_68 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_68
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_69 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import39.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import40.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import41.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import42.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import43.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import31.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import37.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import44.NgIf) && (20 === requestNodeIndex))) { return this._NgIf_20_6.context; }
    if (((token === import45.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_18_4.context; }
    if (((token === import45.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_18_5.context; }
    if (((token === import46.CardContent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._CardContent_31_3.context; }
    if (((token === import38.Icon) && (43 === requestNodeIndex))) { return this._Icon_43_3.context; }
    if (((token === import39.Button) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Button_41_4.context; }
    if (((token === import47.Col) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Col_39_3.context; }
    if (((token === import38.Icon) && (54 === requestNodeIndex))) { return this._Icon_54_3.context; }
    if (((token === import39.Button) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Button_52_4.context; }
    if (((token === import47.Col) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Col_50_3.context; }
    if (((token === import48.Note) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Note_63_3.context; }
    if (((token === import47.Col) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Col_61_3.context; }
    if (((token === import47.Row) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Row_37_3.context; }
    if (((token === import46.Card) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Card_16_3.context; }
    if (((token === import49.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._Card_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    if (this._Item_18_4.detectChangesInternal(this,this._el_18,throwOnChange)) { this._appEl_18.componentView.markAsCheckOnce(); }
    this._ItemContent_18_5.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_8:any = this.context.auth.authenticated();
    this._NgIf_20_6.check_ngIf(currVal_8,throwOnChange,false);
    this._NgIf_20_6.detectChangesInternal(this,this._anchor_20,throwOnChange);
    this._CardContent_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this._Row_37_3.detectChangesInternal(this,this._el_37,throwOnChange);
    this._Col_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_10:any = '';
    this._Button_41_4.check_small(currVal_10,throwOnChange,false);
    const currVal_11:any = '';
    this._Button_41_4.check_clear(currVal_11,throwOnChange,false);
    if (this._Button_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    const currVal_12:any = 'thumbs-up';
    this._Icon_43_3.check_name(currVal_12,throwOnChange,false);
    this._Icon_43_3.detectChangesInternal(this,this._el_43,throwOnChange);
    this._Col_50_3.detectChangesInternal(this,this._el_50,throwOnChange);
    const currVal_14:any = '';
    this._Button_52_4.check_small(currVal_14,throwOnChange,false);
    const currVal_15:any = '';
    this._Button_52_4.check_clear(currVal_15,throwOnChange,false);
    if (this._Button_52_4.detectChangesInternal(this,this._el_52,throwOnChange)) { this._appEl_52.componentView.markAsCheckOnce(); }
    const currVal_16:any = 'text';
    this._Icon_54_3.check_name(currVal_16,throwOnChange,false);
    this._Icon_54_3.detectChangesInternal(this,this._el_54,throwOnChange);
    this._Col_61_3.detectChangesInternal(this,this._el_61,throwOnChange);
    this._Note_63_3.detectChangesInternal(this,this._el_63,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset(([] as any[]));
        this._Item_18_4.context._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset(([] as any[]));
        this._Item_18_4.context._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_41_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_52_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.userName,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_23,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._Icon_43_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_43,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_17:any = this._Icon_54_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_54,'hide',currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Icon_43_3.context.ngOnDestroy();
    this._Icon_54_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Featured0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Featured> {
  if ((renderType_Featured === (null as any))) { (renderType_Featured = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_Featured,{})); }
  return new _View_Featured0(viewUtils,parentInjector,declarationEl);
}
class _View_Featured1 extends import1.AppView<any> {
  _el_0:any;
  _Avatar_0_3:import50.Wrapper_Avatar;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import24.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured1,renderType_Featured,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-left','');
    this._Avatar_0_3 = new import50.Wrapper_Avatar();
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import37.TemplateRef_(this._appEl_2,viewFactory_Featured2);
    this._NgIf_2_6 = new import24.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import44.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import51.Avatar) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Avatar_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Avatar_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = this.parent.context.myUser;
    this._NgIf_2_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Featured1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Featured1(viewUtils,parentInjector,declarationEl);
}
class _View_Featured2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured2,renderType_Featured,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'height','50%');
    this.renderer.setElementAttribute(this._el_0,'width','70%');
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.parent.context.myUser.picture,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import52.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Featured2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Featured2(viewUtils,parentInjector,declarationEl);
}