/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './featured';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../services/auth/auth.service';
import * as import10 from 'ionic-angular/components/menu/menu-controller';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/navigation/view-controller';
import * as import22 from 'ionic-angular/components/app/app';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from 'ionic-angular/components/toolbar/toolbar';
import * as import25 from '@angular/common/src/directives/ng_if';
import * as import26 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import27 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import28 from 'ionic-angular/components/navbar/navbar';
import * as import29 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import32 from 'ionic-angular/components/icon/icon';
import * as import33 from 'ionic-angular/components/button/button';
import * as import34 from 'ionic-angular/components/menu/menu-toggle';
import * as import35 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import37 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import38 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import39 from '../../node_modules/ionic-angular/components/note/note.ngfactory';
import * as import40 from 'ionic-angular/util/keyboard';
import * as import41 from '@angular/core/src/zone/ng_zone';
import * as import42 from 'ionic-angular/components/tabs/tabs';
import * as import43 from 'ionic-angular/util/form';
import * as import44 from 'ionic-angular/components/item/item-reorder';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from 'ionic-angular/components/card/card';
import * as import47 from 'ionic-angular/components/grid/grid';
import * as import48 from 'ionic-angular/components/note/note';
import * as import49 from 'ionic-angular/components/content/content';
import * as import50 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import51 from 'ionic-angular/components/avatar/avatar';
import * as import52 from '@angular/core/src/security';
export class Wrapper_Featured {
  context:import0.Featured;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.Featured(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_Featured_Host:import2.RenderComponentType = (null as any);
class _View_Featured_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Featured_0_4:Wrapper_Featured;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured_Host0,renderType_Featured_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-featured',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Featured0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Featured_0_4 = new Wrapper_Featured(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AuthService),this.parentInjector.get(import10.MenuController));
    this._appEl_0.initComponent(this._Featured_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Featured_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Featured) && (0 === requestNodeIndex))) { return this._Featured_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Featured_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Featured_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Featured_Host === (null as any))) { (renderType_Featured_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Featured_Host0(viewUtils,parentInjector,declarationEl);
}
export const FeaturedNgFactory:import12.ComponentFactory<import0.Featured> = new import12.ComponentFactory<import0.Featured>('page-featured',viewFactory_Featured_Host0,import0.Featured);
const styles_Featured:any[] = ([] as any[]);
var renderType_Featured:import2.RenderComponentType = (null as any);
class _View_Featured0 extends import1.AppView<import0.Featured> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import15.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _ToolbarTitle_6_4:import16.Wrapper_ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _ToolbarItem_9_3:import17.Wrapper_ToolbarItem;
  _query_Button_9_0:import18.QueryList<any>;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import15.Wrapper_NgIf;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import15.Wrapper_NgIf;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured0,renderType_Featured,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'bar','');
    this.renderer.setElementAttribute(this._el_2,'bar-header','');
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import22.App),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import23.TemplateRef_(this._appEl_4,viewFactory_Featured1);
    this._NgIf_4_6 = new import15.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_6 = new import3.AppElement(6,2,this,this._el_6);
    var compView_6:any = import16.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import16.Wrapper_ToolbarTitle(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import24.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_6.initComponent(this._ToolbarTitle_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'Featured ',(null as any));
    compView_6.create(this._ToolbarTitle_6_4.context,[([] as any[]).concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_9,'right','');
    this._ToolbarItem_9_3 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import24.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_9_0 = new import18.QueryList<any>();
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_11 = new import3.AppElement(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import23.TemplateRef_(this._appEl_11,viewFactory_Featured2);
    this._NgIf_11_6 = new import15.Wrapper_NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n      \n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._appEl_4]),
      ([] as any[]),
      ([] as any[]).concat([this._el_9]),
      ([] as any[]).concat([
        this._text_3,
        this._text_5,
        this._el_6,
        this._text_8,
        this._text_13
      ]
      )
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_16 = new import3.AppElement(16,(null as any),this,this._anchor_16);
    this._TemplateRef_16_5 = new import23.TemplateRef_(this._appEl_16,viewFactory_Featured3);
    this._NgIf_16_6 = new import15.Wrapper_NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._anchor_16
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import25.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import26.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4.context; }
    if (((token === import23.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import25.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import27.ToolbarItem) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ToolbarItem_9_3.context; }
    if (((token === import28.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Navbar_2_4.context; }
    if (((token === import24.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Header_0_3.context; }
    if (((token === import23.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import25.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_2:any = this.context.auth.authenticated();
    this._NgIf_4_6.check_ngIf(currVal_2,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    if (this._ToolbarTitle_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    this._ToolbarItem_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_3:any = this.context.auth.authenticated();
    this._NgIf_11_6.check_ngIf(currVal_3,throwOnChange,false);
    this._NgIf_11_6.detectChangesInternal(this,this._anchor_11,throwOnChange);
    const currVal_4:any = this.context.auth.authenticated();
    this._NgIf_16_6.check_ngIf(currVal_4,throwOnChange,false);
    this._NgIf_16_6.detectChangesInternal(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_Button_9_0.dirty) {
        this._query_Button_9_0.reset([this._appEl_11.mapNestedViews(_View_Featured2,(nestedView:_View_Featured2):any => {
          return [nestedView._Button_0_4.context];
      })]);
      this._ToolbarItem_9_3.context._buttons = this._query_Button_9_0;
      this._query_Button_9_0.notifyOnChanges();
    } }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
}
export function viewFactory_Featured0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Featured> {
  if ((renderType_Featured === (null as any))) { (renderType_Featured = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_Featured,{})); }
  return new _View_Featured0(viewUtils,parentInjector,declarationEl);
}
class _View_Featured1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import29.Wrapper_Button;
  _MenuToggle_0_5:import30.Wrapper_MenuToggle;
  _ToolbarItem_0_6:import17.Wrapper_ToolbarItem;
  _query_Button_0_0:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import31.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured1,renderType_Featured,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'menuToggle','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import29.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import29.Wrapper_Button('','',this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer);
    this._MenuToggle_0_5 = new import30.Wrapper_MenuToggle(this.parent.parentInjector.get(import10.MenuController),new import20.ElementRef(this._el_0),this.parent.parentInjector.get(import21.ViewController,(null as any)),(<_View_Featured0>this.parent)._Navbar_2_4.context);
    this._ToolbarItem_0_6 = new import17.Wrapper_ToolbarItem(this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import24.Toolbar,(null as any)),(<_View_Featured0>this.parent)._Navbar_2_4.context);
    this._query_Button_0_0 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'name','menu');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import31.Wrapper_Icon(this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_0.create(this._Button_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_3
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import33.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_0_4.context; }
    if (((token === import34.MenuToggle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuToggle_0_5.context; }
    if (((token === import27.ToolbarItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ToolbarItem_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_1:any = '';
    this._MenuToggle_0_5.check_menuToggle(currVal_1,throwOnChange,false);
    this._MenuToggle_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._ToolbarItem_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = 'menu';
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_0.dirty) {
        this._query_Button_0_0.reset([this._Button_0_4.context]);
        this._ToolbarItem_0_6.context._buttons = this._query_Button_0_0;
        this._query_Button_0_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = this._MenuToggle_0_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_0_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Featured1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Featured1(viewUtils,parentInjector,declarationEl);
}
class _View_Featured2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Button_0_4:import29.Wrapper_Button;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured2,renderType_Featured,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'logout-btn','');
    this.renderer.setElementAttribute(this._el_0,'primary','');
    this.renderer.setElementAttribute(this._el_0,'round','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import29.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import29.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'Logout',(null as any));
    compView_0.create(this._Button_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = '';
    this._Button_0_4.check_round(currVal_1,throwOnChange,false);
    if (this._Button_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_Featured0>this.parent)._query_Button_9_0.setDirty();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.auth.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Featured2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Featured2(viewUtils,parentInjector,declarationEl);
}
class _View_Featured3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Content_0_4:import35.Wrapper_Content;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import36.Wrapper_Card;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Item_4_4:import37.Wrapper_Item;
  _ItemContent_4_5:import37.Wrapper_ItemContent;
  _query_Label_4_0:import18.QueryList<any>;
  _query_Button_4_1:import18.QueryList<any>;
  _query_Icon_4_2:import18.QueryList<any>;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import15.Wrapper_NgIf;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _CardContent_17_3:import36.Wrapper_CardContent;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _Row_23_3:import38.Wrapper_Row;
  _text_24:any;
  _el_25:any;
  _Col_25_3:import38.Wrapper_Col;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _Button_27_4:import29.Wrapper_Button;
  _text_28:any;
  _el_29:any;
  _Icon_29_3:import31.Wrapper_Icon;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _Col_36_3:import38.Wrapper_Col;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Button_38_4:import29.Wrapper_Button;
  _text_39:any;
  _el_40:any;
  _Icon_40_3:import31.Wrapper_Icon;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _Col_47_3:import38.Wrapper_Col;
  _text_48:any;
  _el_49:any;
  _Note_49_3:import39.Wrapper_Note;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _anchor_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _TemplateRef_55_5:any;
  _NgIf_55_6:import15.Wrapper_NgIf;
  _text_56:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured3,renderType_Featured,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import35.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import35.Wrapper_Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import22.App),this.parentInjector.get(import40.Keyboard),this.parentInjector.get(import41.NgZone),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import42.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_2,'center','');
    this.renderer.setElementAttribute(this._el_2,'width','50%');
    this._Card_2_3 = new import36.Wrapper_Card(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item item-block');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import37.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import37.Wrapper_Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import44.ItemReorder,(null as any)));
    this._ItemContent_4_5 = new import37.Wrapper_ItemContent();
    this._query_Label_4_0 = new import18.QueryList<any>();
    this._query_Button_4_1 = new import18.QueryList<any>();
    this._query_Icon_4_2 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_6 = new import3.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import23.TemplateRef_(this._appEl_6,viewFactory_Featured4);
    this._NgIf_6_6 = new import15.Wrapper_NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'November 5, 1955',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_4_0.reset(([] as any[]));
    this._Item_4_4.context.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4.context,[
      ([] as any[]).concat([this._appEl_6]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_5,
        this._text_7,
        this._el_8,
        this._text_10,
        this._el_11,
        this._text_13
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_15,'src','http://ilovegarciniacambogia.net/wp-content/uploads/2014/02/fast-food.jpg');
    this._text_16 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_2,'ion-card-content',(null as any));
    this._CardContent_17_3 = new import36.Wrapper_CardContent(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'p',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Wait a minute. Wait a minute, Doc. Uhhh... Are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n  ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_2,'ion-row',(null as any));
    this._Row_23_3 = new import38.Wrapper_Row();
    this._text_24 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ion-col',(null as any));
    this._Col_25_3 = new import38.Wrapper_Col();
    this._text_26 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'button',(null as any));
    this.renderer.setElementAttribute(this._el_27,'clear','');
    this.renderer.setElementAttribute(this._el_27,'icon-left','');
    this.renderer.setElementAttribute(this._el_27,'ion-button','');
    this.renderer.setElementAttribute(this._el_27,'small','');
    this._appEl_27 = new import3.AppElement(27,25,this,this._el_27);
    var compView_27:any = import29.viewFactory_Button0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Button_27_4 = new import29.Wrapper_Button((null as any),'',this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_27),this.renderer);
    this._appEl_27.initComponent(this._Button_27_4.context,([] as any[]),compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_29,'name','thumbs-up');
    this.renderer.setElementAttribute(this._el_29,'role','img');
    this._Icon_29_3 = new import31.Wrapper_Icon(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_29),this.renderer);
    this._text_30 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'12 Likes',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_27.create(this._Button_27_4.context,[([] as any[]).concat([
        this._text_28,
        this._el_29,
        this._text_30,
        this._el_31,
        this._text_33
      ]
    )],(null as any));
    this._text_34 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_23,'ion-col',(null as any));
    this._Col_36_3 = new import38.Wrapper_Col();
    this._text_37 = this.renderer.createText(this._el_36,'\n      ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'button',(null as any));
    this.renderer.setElementAttribute(this._el_38,'clear','');
    this.renderer.setElementAttribute(this._el_38,'icon-left','');
    this.renderer.setElementAttribute(this._el_38,'ion-button','');
    this.renderer.setElementAttribute(this._el_38,'small','');
    this._appEl_38 = new import3.AppElement(38,36,this,this._el_38);
    var compView_38:any = import29.viewFactory_Button0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Button_38_4 = new import29.Wrapper_Button((null as any),'',this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_38),this.renderer);
    this._appEl_38.initComponent(this._Button_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_40,'name','text');
    this.renderer.setElementAttribute(this._el_40,'role','img');
    this._Icon_40_3 = new import31.Wrapper_Icon(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_40),this.renderer);
    this._text_41 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'4 Comments',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_38.create(this._Button_38_4.context,[([] as any[]).concat([
        this._text_39,
        this._el_40,
        this._text_41,
        this._el_42,
        this._text_44
      ]
    )],(null as any));
    this._text_45 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._text_46 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_23,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_47,'center','');
    this.renderer.setElementAttribute(this._el_47,'text-center','');
    this._Col_47_3 = new import38.Wrapper_Col();
    this._text_48 = this.renderer.createText(this._el_47,'\n      ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_47,'ion-note',(null as any));
    this._Note_49_3 = new import39.Wrapper_Note();
    this._text_50 = this.renderer.createText(this._el_49,'\n        11h ago\n      ',(null as any));
    this._text_51 = this.renderer.createText(this._el_47,'\n    ',(null as any));
    this._text_52 = this.renderer.createText(this._el_23,'\n  ',(null as any));
    this._text_53 = this.renderer.createText(this._el_2,'\n\n',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n    \n\n\n',(null as any));
    this._anchor_55 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_55 = new import3.AppElement(55,0,this,this._anchor_55);
    this._TemplateRef_55_5 = new import23.TemplateRef_(this._appEl_55,viewFactory_Featured5);
    this._NgIf_55_6 = new import15.Wrapper_NgIf(this._appEl_55.vcRef,this._TemplateRef_55_5);
    this._text_56 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_0.create(this._Content_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_54,
        this._appEl_55,
        this._text_56
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._anchor_55,
      this._text_56
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import25.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    if (((token === import45.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_4_4.context; }
    if (((token === import45.ItemContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_4_5.context; }
    if (((token === import46.CardContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._CardContent_17_3.context; }
    if (((token === import32.Icon) && (29 === requestNodeIndex))) { return this._Icon_29_3.context; }
    if (((token === import33.Button) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Button_27_4.context; }
    if (((token === import47.Col) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Col_25_3.context; }
    if (((token === import32.Icon) && (40 === requestNodeIndex))) { return this._Icon_40_3.context; }
    if (((token === import33.Button) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Button_38_4.context; }
    if (((token === import47.Col) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Col_36_3.context; }
    if (((token === import48.Note) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Note_49_3.context; }
    if (((token === import47.Col) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Col_47_3.context; }
    if (((token === import47.Row) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Row_23_3.context; }
    if (((token === import46.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Card_2_3.context; }
    if (((token === import23.TemplateRef) && (55 === requestNodeIndex))) { return this._TemplateRef_55_5; }
    if (((token === import25.NgIf) && (55 === requestNodeIndex))) { return this._NgIf_55_6.context; }
    if (((token === import49.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Content_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._Card_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Item_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    this._ItemContent_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_1:any = this.parent.context.auth.authenticated();
    this._NgIf_6_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_6_6.detectChangesInternal(this,this._anchor_6,throwOnChange);
    this._CardContent_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    this._Row_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Col_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_3:any = '';
    this._Button_27_4.check_small(currVal_3,throwOnChange,false);
    const currVal_4:any = '';
    this._Button_27_4.check_clear(currVal_4,throwOnChange,false);
    if (this._Button_27_4.detectChangesInternal(this,this._el_27,throwOnChange)) { this._appEl_27.componentView.markAsCheckOnce(); }
    const currVal_5:any = 'thumbs-up';
    this._Icon_29_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    this._Col_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_7:any = '';
    this._Button_38_4.check_small(currVal_7,throwOnChange,false);
    const currVal_8:any = '';
    this._Button_38_4.check_clear(currVal_8,throwOnChange,false);
    if (this._Button_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    const currVal_9:any = 'text';
    this._Icon_40_3.check_name(currVal_9,throwOnChange,false);
    this._Icon_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    this._Col_47_3.detectChangesInternal(this,this._el_47,throwOnChange);
    this._Note_49_3.detectChangesInternal(this,this._el_49,throwOnChange);
    const currVal_11:boolean = !this.parent.context.auth.authenticated();
    this._NgIf_55_6.check_ngIf(currVal_11,throwOnChange,false);
    this._NgIf_55_6.detectChangesInternal(this,this._anchor_55,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset(([] as any[]));
        this._Item_4_4.context._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset(([] as any[]));
        this._Item_4_4.context._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_27_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_38_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_0_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = import4.interpolate(1,'',this.parent.context.userName,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._Icon_29_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_29,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_10:any = this._Icon_40_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_40,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_29_3.context.ngOnDestroy();
    this._Icon_40_3.context.ngOnDestroy();
    this._Content_0_4.context.ngOnDestroy();
  }
}
function viewFactory_Featured3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Featured3(viewUtils,parentInjector,declarationEl);
}
class _View_Featured4 extends import1.AppView<any> {
  _el_0:any;
  _Avatar_0_3:import50.Wrapper_Avatar;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured4,renderType_Featured,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-left','');
    this._Avatar_0_3 = new import50.Wrapper_Avatar();
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'height','50%');
    this.renderer.setElementAttribute(this._el_2,'width','70%');
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import51.Avatar) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Avatar_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Avatar_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.parent.context.auth.user.picture,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import52.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Featured4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Featured4(viewUtils,parentInjector,declarationEl);
}
class _View_Featured5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Content_0_4:import35.Wrapper_Content;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Button_2_4:import29.Wrapper_Button;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Featured5,renderType_Featured,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import35.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import35.Wrapper_Content(this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import22.App),this.parent.parentInjector.get(import40.Keyboard),this.parent.parentInjector.get(import41.NgZone),this.parent.parentInjector.get(import21.ViewController,(null as any)),this.parent.parentInjector.get(import42.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'block','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import29.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import29.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'Login',(null as any));
    compView_2.create(this._Button_2_4.context,[([] as any[]).concat([this._text_3])],(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_2_4.context; }
    if (((token === import49.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Content_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = '';
    this._Button_2_4.check_block(currVal_2,throwOnChange,false);
    if (this._Button_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.context.ngAfterContentInit(); } }
    const currVal_0:any = this._Content_0_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.context.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.auth.login()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Featured5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Featured5(viewUtils,parentInjector,declarationEl);
}