/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './profile';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../services/auth/auth.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/navigation/view-controller';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from 'ionic-angular/navigation/nav-controller';
import * as import25 from 'ionic-angular/components/menu/menu-controller';
import * as import26 from 'ionic-angular/components/toolbar/toolbar';
import * as import27 from '@angular/core/src/linker/template_ref';
import * as import28 from 'ionic-angular/components/icon/icon';
import * as import29 from 'ionic-angular/components/button/button';
import * as import30 from 'ionic-angular/components/menu/menu-toggle';
import * as import31 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import32 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import33 from 'ionic-angular/components/navbar/navbar';
import * as import34 from '@angular/common/src/directives/ng_if';
import * as import35 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from 'ionic-angular/components/content/content';
import * as import40 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import41 from 'ionic-angular/components/card/card';
import * as import42 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import43 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import44 from 'ionic-angular/util/form';
import * as import45 from 'ionic-angular/components/item/item-reorder';
import * as import46 from 'ionic-angular/components/avatar/avatar';
import * as import47 from 'ionic-angular/components/item/item';
import * as import48 from '@angular/core/src/security';
export class Wrapper_Profile {
  context:import0.Profile;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.Profile(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_Profile_Host:import2.RenderComponentType = (null as any);
class _View_Profile_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Profile_0_4:Wrapper_Profile;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Profile_Host0,renderType_Profile_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-profile',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Profile0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Profile_0_4 = new Wrapper_Profile(this.parentInjector.get(import8.AuthService));
    this._appEl_0.initComponent(this._Profile_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Profile_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Profile) && (0 === requestNodeIndex))) { return this._Profile_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Profile_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Profile_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Profile_Host === (null as any))) { (renderType_Profile_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Profile_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProfileNgFactory:import10.ComponentFactory<import0.Profile> = new import10.ComponentFactory<import0.Profile>('page-profile',viewFactory_Profile_Host0,import0.Profile);
const styles_Profile:any[] = ([] as any[]);
var renderType_Profile:import2.RenderComponentType = (null as any);
class _View_Profile0 extends import1.AppView<import0.Profile> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import13.Wrapper_Button;
  _MenuToggle_5_5:import14.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import15.Wrapper_ToolbarItem;
  _query_Button_5_0:import16.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import17.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import18.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import19.Wrapper_NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import19.Wrapper_NgIf;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Profile0,renderType_Profile,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  \n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import22.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import23.App),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import24.NavController,(null as any)),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import13.Wrapper_Button('','',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import14.Wrapper_MenuToggle(this.parentInjector.get(import25.MenuController),new import21.ElementRef(this._el_5),this.parentInjector.get(import22.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import15.Wrapper_ToolbarItem(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import16.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import17.Wrapper_Icon(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,3,this,this._el_10);
    var compView_10:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'Profile',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._el_10,
        this._text_12
      ]
      )
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_15 = new import3.AppElement(15,(null as any),this,this._anchor_15);
    this._TemplateRef_15_5 = new import27.TemplateRef_(this._appEl_15,viewFactory_Profile1);
    this._NgIf_15_6 = new import19.Wrapper_NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_17 = new import3.AppElement(17,(null as any),this,this._anchor_17);
    this._TemplateRef_17_5 = new import27.TemplateRef_(this._appEl_17,viewFactory_Profile2);
    this._NgIf_17_6 = new import19.Wrapper_NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import29.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import30.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import31.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import32.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import33.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Navbar_3_4.context; }
    if (((token === import26.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Header_1_3.context; }
    if (((token === import27.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import34.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import27.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import34.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_7_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_7:boolean = !this.context.auth.authenticated();
    this._NgIf_15_6.check_ngIf(currVal_7,throwOnChange,false);
    this._NgIf_15_6.detectChangesInternal(this,this._anchor_15,throwOnChange);
    const currVal_8:any = this.context.auth.authenticated();
    this._NgIf_17_6.check_ngIf(currVal_8,throwOnChange,false);
    this._NgIf_17_6.detectChangesInternal(this,this._anchor_17,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Profile0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Profile> {
  if ((renderType_Profile === (null as any))) { (renderType_Profile = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_Profile,{})); }
  return new _View_Profile0(viewUtils,parentInjector,declarationEl);
}
class _View_Profile1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Content_0_4:import35.Wrapper_Content;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Button_2_4:import13.Wrapper_Button;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Profile1,renderType_Profile,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import35.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import35.Wrapper_Content(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'block','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import13.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'Login',(null as any));
    compView_2.create(this._Button_2_4.context,[([] as any[]).concat([this._text_3])],(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n  \n',(null as any));
    compView_0.create(this._Content_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_2_4.context; }
    if (((token === import39.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Content_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = '';
    this._Button_2_4.check_block(currVal_2,throwOnChange,false);
    if (this._Button_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.context.ngAfterContentInit(); } }
    const currVal_0:any = this._Content_0_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.context.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.auth.login()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Profile1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Profile1(viewUtils,parentInjector,declarationEl);
}
class _View_Profile2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Content_0_4:import35.Wrapper_Content;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import40.Wrapper_Card;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import19.Wrapper_NgIf;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Button_7_4:import13.Wrapper_Button;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Profile2,renderType_Profile,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import35.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import35.Wrapper_Content(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_2_3 = new import40.Wrapper_Card(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import27.TemplateRef_(this._appEl_4,viewFactory_Profile3);
    this._NgIf_4_6 = new import19.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n  \n  ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'block','');
    this.renderer.setElementAttribute(this._el_7,'ion-button','');
    this._appEl_7 = new import3.AppElement(7,0,this,this._el_7);
    var compView_7:any = import13.viewFactory_Button0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Button_7_4 = new import13.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_7),this.renderer);
    this._appEl_7.initComponent(this._Button_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'Logout',(null as any));
    compView_7.create(this._Button_7_4.context,[([] as any[]).concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n  \n',(null as any));
    compView_0.create(this._Content_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_6,
        this._el_7,
        this._text_9
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import34.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import41.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Card_2_3.context; }
    if (((token === import29.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_7_4.context; }
    if (((token === import39.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Content_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._Card_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_1:any = this.parent.context.myUser;
    this._NgIf_4_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    const currVal_3:any = '';
    this._Button_7_4.check_block(currVal_3,throwOnChange,false);
    if (this._Button_7_4.detectChangesInternal(this,this._el_7,throwOnChange)) { this._appEl_7.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_7_4.context.ngAfterContentInit(); } }
    const currVal_0:any = this._Content_0_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.context.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.auth.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Profile2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Profile2(viewUtils,parentInjector,declarationEl);
}
class _View_Profile3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import42.Wrapper_Item;
  _ItemContent_0_5:import42.Wrapper_ItemContent;
  _query_Label_0_0:import16.QueryList<any>;
  _query_Button_0_1:import16.QueryList<any>;
  _query_Icon_0_2:import16.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Avatar_2_3:import43.Wrapper_Avatar;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Profile3,renderType_Profile,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import42.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import42.Wrapper_Item(this.parent.parentInjector.get(import44.Form),this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import45.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import42.Wrapper_ItemContent();
    this._query_Label_0_0 = new import16.QueryList<any>();
    this._query_Button_0_1 = new import16.QueryList<any>();
    this._query_Icon_0_2 = new import16.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this._Avatar_2_3 = new import43.Wrapper_Avatar();
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'h1',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_6,
        this._el_7,
        this._text_9,
        this._el_10,
        this._text_12
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Avatar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Avatar_2_3.context; }
    if (((token === import47.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Item_0_4.context; }
    if (((token === import47.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Avatar_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.parent.parent.context.myUser.picture,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import48.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.parent.context.myUser.nickname,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_8,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.parent.parent.context.myUser.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_11,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Profile3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Profile3(viewUtils,parentInjector,declarationEl);
}